services:
  db:
    image: postgres:17
    container_name: sistemavuelo-db
    environment:
      - POSTGRES_DB=sistemavuelo
      - POSTGRES_USER=sistemavuelo
      - POSTGRES_PASSWORD=sistemavuelo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    name: sistemavuelo-postgres-data